# Generated by Django 3.0.2 on 2020-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technexid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('ques1', models.CharField(max_length=30)),
                ('ques2', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='age',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='name',
        ),
        migrations.AddField(
            model_name='questions',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
