# Generated by Django 3.0.2 on 2020-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200201_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
