# Generated by Django 3.0.2 on 2020-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200201_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(),
        ),
    ]
