# Generated by Django 3.0.2 on 2020-02-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_qid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='age',
            new_name='year',
        ),
    ]
