# Generated by Django 3.0.2 on 2020-02-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200202_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='technexid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
