# Generated by Django 3.0.2 on 2020-02-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200202_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AddField(
            model_name='entry',
            name='submitted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='technexid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
