# Generated by Django 3.0.2 on 2020-02-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200202_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_first',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_last',
            field=models.BooleanField(default=0),
        ),
    ]
