# Generated by Django 3.0.2 on 2020-02-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_question_qno'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option5',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
