# Generated by Django 3.0.2 on 2020-02-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_question_option5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_first',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_last',
            field=models.BooleanField(default=1),
        ),
    ]
