# Generated by Django 3.0.2 on 2020-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200203_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ques1',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ques2',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option5',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
    ]
