# Generated by Django 3.0.2 on 2020-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200204_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mcq', 'mcq'), ('rapidfire', 'rapidfire')], default='mcq', max_length=10),
        ),
    ]
