# Generated by Django 3.0.2 on 2020-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200206_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
