# Generated by Django 3.0.2 on 2020-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200206_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('technexid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
