# Generated by Django 3.0.2 on 2020-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customentry',
            name='ques16',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques17',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques18',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques19',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques20',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques21',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques22',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques23',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques24',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques25',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques26',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques27',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques28',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques29',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customentry',
            name='ques30',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques16',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques17',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques18',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques19',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques20',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques21',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques22',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques23',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques24',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques25',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques26',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques27',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques28',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques29',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='ques30',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
    ]
