# Generated by Django 3.0.2 on 2020-02-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200208_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('half1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='half1', to='main.Participant')),
                ('half2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='half2', to='main.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('clue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Clue')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Winner')),
            ],
        ),
    ]
