# Generated by Django 3.0.2 on 2020-02-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_answer_clue_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClueState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('clue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Clue')),
            ],
        ),
    ]
