# Generated by Django 3.0.2 on 2020-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cluestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='state',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
