# Generated by Django 3.0.2 on 2020-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200213_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='form',
            field=models.BooleanField(default=0),
        ),
    ]
